server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      url: redis://localhost:6379

  application:
    name: user

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/LAPLACE
    driver-class-name: org.mariadb.jdbc.Driver
    username: minyeop
    password: skekd12

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true