spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/LAPLACE
    driver-class-name: org.mariadb.jdbc.Driver
    username: minyeop
    password: skekd12

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.71.5:8761/eureka/
  instance:
    prefer-ip-address: true
