spring:
  config:
    activate:
      on-profile: server

  data:
    redis:
      url: redis://172.31.45.57:6379

  application:
    name: user

  datasource:
    url: jdbc:mariadb://laplace.c3m6o22cgj7p.ap-northeast-2.rds.amazonaws.com:3306/LAPLACE
    driver-class-name: org.mariadb.jdbc.Driver
    username: minyeop
    password: skekd12

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.71.5:8761/eureka/
  instance:
    hostname: 3.34.71.5
    prefer-ip-address: true