server:
  port: 8080

spring:
  application:
    name: gateway

  data:
    redis:
      #host: 172.31.45.57
      host: localhost
      port: 6379

  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://3.34.71.5:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    #hostname: 3.34.71.5
    hostname: 127.0.0.1
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway, info, routes, health
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: YXNma2RqaDI0bzM1cmlqc2Rsa2ZmOTAyMzQ1rERFsdfwerfDAGqrtgSD1w123adfvdrgFGBKFVsdfl1o2sasf4512eaggfdf
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: TRACE

