server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: cart-route
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
        - id: search-route
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.34.71.5:8761/eureka/


