spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.71.5:8761/eureka/
  instance:
    prefer-ip-address: true


