server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: gateway, info, routes, health
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true