version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: react-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
